version: '3.8'

services:
  springboot:
    image: shirishamitti/spring-mongo-docker-compose:latest
    environment:
    - MONGO_DB_HOSTNAME=mymongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    #ports:
     # - 1332:8080
    #working_dir: /opt/app
    depends_on:
      - mymongo
    networks:
    - springappnetwork  

  mymongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
      - mongodb:/data/db
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    external: true
    
networks:
  springappnetwork:
    external: true
